// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using transpositionAPI.Context;

namespace transpositionAPI.Migrations
{
    [DbContext(typeof(DBContexto))]
    [Migration("20200316145449_Transposition_M1")]
    partial class Transposition_M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("transpositionAPI.Models.TAcordes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcordesCromaticas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("acordesCromaticasMayores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("acordesCromaticasMenores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("acordesSeptimaMayor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("acordesSeptimaMenor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("acordes");
                });

            modelBuilder.Entity("transpositionAPI.Models.TNotas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("notasCromaticas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notasCromaticasMayores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notasCromaticasMenores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notasCromaticasSeptimaMayores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notasCromaticasSeptimaMenores")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("notas");
                });
#pragma warning restore 612, 618
        }
    }
}
